### ISSUE TITLE
Scratch Freestyle Zone

### ISSUE THREAD

**Issue by DolphinDTM** [bemusic/bmson-spec#7]
Proposed by @mechacrash to me.
This idea is taken from classic beatmania.

It is a kind of longnote that only appears on turntable.
Instead of continuing to spin the turntable, you can scratch as you will.

Should we include this in the specification, or make implementation player-dependant?

**Comment by dtinth** [comment]
Personally, I prefer it the main bmson specification to be player-agnostic. I think each mechanic should be specified, but as feature modules which a player can choose to support or not support.

As for data format, I think there are two categories:
- **Notes that can act like normal notes if unsupported.** This should go into the normal `notes` section. Examples are: [green notes from DJMAX](https://www.youtube.com/watch?v=aXbMpcuidE4), [different noteskin for each player in PIU](https://www.youtube.com/watch?v=Ygu2AtYPg5o).
- **Notes that cannot be treated like normal notes if unsupported.** I think they should have their own section, because they are not interchangeable with normal notes. e.g. `hidden_notes`, `landmines`.

I'm not sure how to treat scratch freestyle zone, but I think it should be in category two. Otherwise, player would have to spin the scratch continuously during that zone.

I'm not sure about the scoring mechanism though.

**Comment by gatchamix** [comment]
I don't believe freezone scratching rewards any points - it's simply "for fun". For this reason, I agree that they should be treated as category 2.

A further consideration to make is a specification for implementation. The issue is that (in the original game), freezone scratches allowed direction and speed of scratching to change the sample.
Obviously, this isn't applicable to binary input (keyboards), but for analogue turntables on a IIDX style controller, this needs to be discussed.

**Comment by DolphinDTM** [comment]
There is also confusion about how someone would apply two samples (one for TT clockwise and one for TT counter-clockwise) to the freezone using bmson. 

My first solution would be to simply have overlapping longnotes with `kind=free` specified.
Another solution would be adding a completely new section to the bmson file that looks similar to the "lines" part, except it would be specifically used for freezone events rather than barline events.

**Comment by suitougreentea** [comment]
If we implement it, I prefer longnotes with `"kind": "free"` (or something like), but what should we do with keysounds?

**Comment by DolphinDTM** [comment]
This is why I propose something like this:

```
"freezone": [
        {
                "y": 240,
                "l": 60,
                "up": sample01.wav,
                "down": sample02.wav
        }
]
```

or something similar.

**Comment by DolphinDTM** [comment]
Freezone scratch is ultimately pointless and would serve no purpose other than aesthetic reasons. I think it is fair to close this.
