### ISSUE TITLE
About MIDI key sound support

### ISSUE THREAD

**Issue by kuna** [bemusic/bmson-spec#8]
Hi, recently I heard new bms emulator is working in progress and I'm very glad to hear that. But I found there's no support about midi related support(like keysound pitch ...) in bmson format.
Recently I'm working on with *.vos format, which is quite old rhythm game char format based on midi, personally, and I'm integrating that format with my own project. And as vos format is quite old one, I was planning to export this file in 'new playable file format I'm developing myself', and now I'd more like to export as bmson format.

I wish this new bms format, bmson, can support midi file format for playing, as there's no reason to unsupport. just more metadata and pitch data can make bmson format support midi.

**Comment by dtinth** [comment]
Hello and thanks for your comment.

Concerning MIDI (this is only my opinion, and doesn’t represent the opinion of the team), bmson is mostly based on a sampler/audio clips. Supporting MIDI means more implementation effort by the bmson players. We also have to work out how MIDI notes gets turned into sound so that the same sound may be reproduced by MIDI players. Personally, I would try to avoid the situation where the same bmson file sounds different on different machines, due to different synthesizers/soundfonts.

Despite that, I am interested to hear what the use cases are that you think supporting MIDI will help. For example: Note pitch and note velocity (volume), these can all be implemented without having to implement full MIDI support.

**Comment by kuna** [comment]
Thanks for your nice comment. I also agree midi sound is different from machine so that's not suitable for standard format. But I just suggest midi sound format in case of need like vos file format.

Anyway, the new bmson format is quite extensible so I think I can apply midi key sound although it may be non-standard. Thanks for your work for this nice standard. And thanks for consideration for note pitch data.
